12122024/3

diff --git a/minilibx-linux/configure b/minilibx-linux/configure
--- a/minilibx-linux/configure
+++ b/minilibx-linux/configure
@@ -1,5 +1,4 @@
 #!/usr/bin/env sh
-
 set -e
 
 BOLD="\033[1m"
@@ -81,46 +80,41 @@ clean(){
 }
 
 parse_args(){
-	case "$1" in
-		--help | -h)
-			show_help
-			exit 0;;
-		clean)
-			clean
-			exit 0;;
-		"") return;;
-		*)
-			log_error "unknown command \"$1\"\nRun \"./configure --help\" for usage."
-			exit 1;;
-	esac
+    case "$1" in
+        --help | -h)
+            show_help
+            exit 0;;
+        clean)
+            clean
+            exit 0;;
+        "") return;;
+        *)
+            log_error "unknown command \"$1\"\nRun \"./configure --help\" for usage."
+            exit 1;;
+    esac
 }
 
 main(){
-	local xlib_inc="$(get_xlib_include_path)"
+    local xlib_inc="$(get_xlib_include_path)"
 
-	case $(uname) in
-		FreeBSD) MAKE=gmake ;;
-		*) MAKE=make ;;
-	esac
+    case $(uname) in
+        FreeBSD) MAKE=gmake ;;
+        *) MAKE=make ;;
+    esac
 
-	parse_args "$@"
-	if [ -z "$xlib_inc" ]; then
-		log_error "Can't find a suitable X11 include directory."
-		exit 1
-	fi
-	log_info "Found X11 include path directory: $xlib_inc"
+    parse_args "$@"
+    if [ -z "$xlib_inc" ]; then
+        log_error "Can't find a suitable X11 include directory."
+        exit 1
+    fi
+    log_info "Found X11 include path directory: $xlib_inc"
 
-	log_info 'Generate "makefile.gen" from template "makefile.mk"'
-		echo "INC=$xlib_inc"  	 	    	>  Makefile.gen 
-		cat Makefile.mk | grep -v %%%%  	>> Makefile.gen
-	log_info 'Generate "test/makefile.gen" from template "test/makefile.mk"'
-		echo "INC=$xlib_inc"				>  test/Makefile.gen
-		cat test/Makefile.mk | grep -v %%%% >> test/Makefile.gen
+    log_info 'Generate "makefile.gen" from template "makefile.mk"'
+    echo "INC=$xlib_inc" > Makefile.gen 
+    cat Makefile.mk | grep -v %%%% >> Makefile.gen
 
-	log_info 'Execute "make all" from file "makefile.gen"'
-		${MAKE} -f Makefile.gen all
-	log_info 'Execute "make all" from file "test/makefile.gen"'
-		(cd test ; ${MAKE} -f Makefile.gen all )
+    log_info 'Execute "make all" from file "makefile.gen"'
+    ${MAKE} -f Makefile.gen all
 }
 
 main "$@"
